In [5]:
import pandas as pd

In [7]:
dataset = pd.read_csv("C:/Users/ADMIN/Desktop/FBS/Data Science/Data sets/Restaurant_Reviews.tsv", delimiter="\t")

In [9]:
dataset.head()

                                              Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [10]:
dataset.iloc[3]['Review']

'Stopped by during the late May bank holiday off Rick Steve recommendation and loved it.'

In [11]:
dataset.shape

(1000, 2)

In [12]:
dataset['Liked'].value_counts()

Liked
1    500
0    500
Name: count, dtype: int64

In [13]:
import spacy
nlp= spacy.load("en_core_web_sm")

In [14]:
print(nlp.Defaults.stop_words)

{'seeming', 'anyhow', 'we', '‘ll', 'as', 'made', 'over', 'bottom', "'s", '’re', 'it', 'unless', 'up', 'sometime', 'of', 'them', 'every', 'more', 'during', 'my', 'very', 'at', 'except', 'always', 'nine', '’ll', 'they', 'those', 'yourselves', 'no', 'same', 'fifty', 'back', 'himself', 'used', 'when', 'did', 'until', 'here', 'make', 'another', 'this', 'seems', 'also', 'just', 'against', 'herein', 'by', 'while', 'nevertheless', 'forty', "'m", 'perhaps', 'otherwise', 'n’t', 'have', 'thence', 'themselves', 'sometimes', 'hence', 'her', 'such', 'latterly', 'eleven', 'twelve', 'without', 'became', 'moreover', 'in', 'among', '’m', 'must', 'its', 'indeed', 'beyond', "'d", 'somewhere', '‘m', 'please', 'seemed', 'nothing', 'none', 'eight', 'herself', 'two', 'than', 'to', 'others', 'us', 'n‘t', '‘s', 'ourselves', 'his', 'should', 'yourself', 'besides', 'get', 'toward', 'does', 'above', 'why', 'be', 'thereby', 'twenty', 'now', 'your', 'along', 'elsewhere', 'most', 'nor', 'own', 'enough', 'neither', 'thru', 'move', 'several', 'a', 'below', 'being', 'either', 'across', 'the', 'wherein', 'well', 'go', 'meanwhile', 'but', 'would', 'been', '’d', 'almost', 'and', 'an', 'wherever', 'hundred', 'or', 'formerly', 'i', 'put', 'although', 'mostly', 'whatever', 'somehow', 'if', 'really', 'name', 'anything', 'do', 'before', "'re", 'how', 'him', 'done', 'thereafter', 'through', 'even', 'empty', 'least', 'not', 'so', 'ca', 'these', 'quite', 'all', 'regarding', '’s', 'sixty', 'many', 'throughout', 'between', 'whenever', 'though', 'about', 'front', 'on', 'alone', 'rather', 'are', 'only', 'who', '‘re', 'that', 'into', '‘ve', 'whom', '’ve', 'with', 'whereupon', 'nowhere', 'upon', 'thus', 'per', 'yet', 'once', 'there', 'becoming', 'yours', 'take', 'whereafter', 'since', 'hereby', 'can', 'using', 'me', 'down', "n't", 'within', 'any', 'six', 'three', 'whence', 'towards', 'much', 'noone', 'whither', 'myself', 'next', 'other', 'each', 'something', 'never', 'am', 'ours', 'seem', 'may', 'whereby', 'often', 'five', 'which', 'else', 'serious', 'onto', 'whoever', 'keep', 'few', 'what', 'ten', 'third', 'our', 'beside', 'latter', 'afterwards', 'amount', 'give', 'part', 'whereas', 'beforehand', 'anyone', 'doing', '‘d', 'thereupon', 'mine', 'together', 'were', 'behind', 'last', 'someone', 'anywhere', 'then', 'full', 'everyone', 'cannot', 'could', 'their', 'after', 'might', 'via', 'less', 'become', 'former', 'again', 'everywhere', 'under', 'amongst', 'becomes', 'everything', 'call', 'various', 'is', 'had', 'off', 'therein', 'will', 're', 'fifteen', 'hereafter', 'however', 'where', 'out', 'still', 'namely', 'anyway', 'top', 'around', 'has', 'show', "'ll", 'some', 'due', 'for', 'side', 'already', 'nobody', 'both', 'she', 'ever', 'hers', 'because', 'hereupon', 'whether', 'see', 'whose', 'whole', 'itself', 'first', 'too', 'you', 'further', 'he', 'one', 'from', 'was', 'four', 'therefore', "'ve", 'say'}

In [15]:
len(nlp.Defaults.stop_words)

326

In [16]:
words = ['not','never', 'nothing']
for x in words: 
    nlp.Defaults.stop_words.remove(x)
    nlp.vocab[x].is_stop=False

In [17]:
len(nlp.Defaults.stop_words)

323

In [18]:
all_stop_words = nlp.Defaults.stop_words

In [19]:
import re
output = []

In [20]:
for i in range(0,1000):
    review = dataset['Review'][i]
    review = re.sub('[^a-zA-Z0-9]',' ',review)
    
    doc = nlp(review)
    processed_str =[]
    for token in doc:
        if token not in all_stop_words:
            processed_str.append(token.lemma_)
    processed_str = ' '.join(processed_str)
    output.append(processed_str)

In [21]:
output

['wow     love this place',
 'Crust be not good',
 'not tasty and the texture be just nasty',
 'stop by during the late May bank holiday off Rick Steve recommendation and love it',
 'the selection on the menu be great and so be the price',
 'now I be get angry and I want my damn pho',
 'honeslty it didn t taste that fresh  ',
 'the potato be like rubber and you could tell they have be make up ahead of time be keep under a warm',
 'the fry be great too',
 'a great touch',
 'service be very prompt',
 'would not go back',
 'the cashier have no care what so ever on what I have to say it still end up be wayyy overpriced',
 'I try the Cape Cod ravoli   chicken   with cranberry    mmmm',
 'I be disgusted because I be pretty sure that be human hair',
 'I be shock because no sign indicate cash only',
 'highly recommend',
 'Waitress be a little slow in service',
 'this place be not worth your time   let alone Vegas',
 'do not like at all',
 'the Burrittos Blah',
 'the food   amazing',
 'service be also cute',
 'I could care less     the interior be just beautiful',
 'so they perform',
 'that s right     the red velvet cake      ohhh this stuff be so good',
 '   they never bring a salad we ask for',
 'this hole in the wall have great mexican street taco   and friendly staff',
 'take an hour to get our food only 4 table in restaurant my food be Luke warm   our sever be run around like he be totally overwhelmed',
 'the bad be the salmon sashimi',
 'also there be combo like a burger   fry   and beer for 23 which be a decent deal',
 'this be like the final blow',
 'I find this place by accident and I could not be happy',
 'seem like a good quick place to grab a bite of some familiar pub food   but do yourself a favor and look elsewhere',
 'overall   I like this place a lot',
 'the only redeem quality of the restaurant be that it be very inexpensive',
 'ample portion and good price',
 'poor service   the waiter make I feel like I be stupid every time he come to the table',
 'my first visit to Hiro be a delight',
 'service suck',
 'the shrimp tender and moist',
 'there be not a deal good enough that would drag I into that establishment again',
 'hard to judge whether these side be good because we be gross out by the melt styrofoam and didn t want to eat it for fear of get sick',
 'on a positive note   our server be very attentive and provide great service',
 'frozen puck of disgust   with some of the bad people behind the register',
 'the only thing I do like be the prime rib and dessert section',
 'it s too bad the food be so damn generic',
 'the burger be good beef   cook just right',
 'if you want a sandwich just go to any firehouse     ',
 'my side greek salad with the greek dressing be so tasty   and the pita and hummus be very refreshing',
 'we order the duck rare and it be pink and tender on the inside with a nice char on the outside',
 'he come run after we when he realize my husband have leave his sunglass on the table',
 'their chow mein be so good',
 'they have horrible attitude towards customer   and talk down to each one when customer don t enjoy their food',
 'the portion be huge',
 'love it    friendly server   great food   wonderful and imaginative menu',
 'the Heart Attack Grill in downtown Vegas be an absolutely flat lined excuse for a restaurant',
 'not much seafood and like 5 string of pasta at the bottom',
 'the salad have just the right amount of sauce to not over power the scallop   which be perfectly cook',
 'the rip banana be not only rip   but petrified and tasteless',
 'at least think to refill my water before I struggle to wave you over for 10 minute',
 'this place receive star for their appetizer   ',
 'the cocktail be all handmade and delicious',
 'we d definitely go back here again',
 'we be so glad we find this place',
 'great food and service   huge portion and they give a military discount',
 'always a great time at Dos gringo',
 'update      go back for a second time and it be still just as amazing',
 'we get the food and apparently they have never hear of salt and the batter on the fish be chewy',
 'a great way to finish a great',
 'the deal include 5 tasting and 2 drink   and Jeff go above and beyond what we expect',
 '   really   really good rice   all the time',
 'the service be meh',
 'it take over 30 min to get their milkshake   which be nothing more than chocolate milk',
 'I guess I should have know that this place would suck   because it be inside of the Excalibur   but I didn t use my common sense',
 'the scallop dish be quite appalling for value as well',
 '2 time    very Bad Customer Service  ',
 'the sweet potato fry be very good and season well',
 'today be the second time I ve be to their lunch buffet and it be pretty good',
 'there be so much good food in Vegas that I feel cheated for waste an eat opportunity by go to Rice and Company',
 'come here be like experience an underwhelme relationship where both party can t wait for the other person to ask to break up',
 'walk in and the place smell like an old grease trap and only 2 other there eat',
 'the turkey and roast beef be bland',
 'this place have it',
 'the pan cake everyone be rave about taste like a sugary disaster tailor to the palate of a six year old',
 'I love the Pho and the spring roll oh so yummy you have to try',
 'the poor batter to meat ratio make the chicken tender very unsatisfying',
 'all I have to say be the food be amazing   ',
 'omelet be to die for',
 'everything be fresh and delicious',
 'in summary   this be a largely disappointing dining experience',
 'it s like a really sexy party in your mouth   where you re outrageously flirt with the hot person at the party',
 'never be to Hard Rock Casino before   will never ever step forward in it again',
 'good breakfast buffet   ',
 'say bye bye to your tip lady',
 'we ll never go again',
 'will be back again',
 'food arrive quickly',
 'it be not good',
 'on the up side   their cafe serve really good food',
 'our server be fantastic and when he find out the wife love roasted garlic and bone marrow   he add extra to our meal and another marrow to go',
 'the only good thing be our waiter   he be very helpful and keep the bloddy mary s come',
 'Best Buffet in town   for the price you can not beat it',
 'I love their mussel cook in this wine reduction   the duck be tender   and their potato dish be delicious',
 'this be one of the well buffet that I have be to',
 'so we go to Tigerlilly and have a fantastic afternoon',
 'the food be delicious   our bartender be attentive and personable and we get a great deal',
 'the ambience be wonderful and there be music play',
 'will go back next trip out',
 'Sooooo good  ',
 'REAL sushi lover   let s be honest    Yama be not that good',
 'at least 40min pass in between we order and the food arrive   and it wasn t that busy',
 'this be a really fantastic Thai restaurant which be definitely worth a visit',
 'nice   spicy and tender',
 'good price',
 'check it out',
 'it be pretty gross',
 'I ve have well atmosphere',
 'kind of hard to mess up a steak but they do',
 'although I very much like the look and sound of this place   the actual experience be a bit disappointing',
 'I just don t know how this place manage to serve the blandest food I have ever eat when they be prepare indian cuisine',
 'bad service to boot   but that be the least of their worry',
 'service be fine and the waitress be friendly',
 'the guy all have steak   and our steak love son who have have steak at the good and bad place say it be the good steak he s ever eat',
 'we think you d have to venture far away to get good sushi   but this place really hit the spot that night',
 'host staff be   for lack of a well word   BITCHES',
 'Bland     not a like this place for a number of reason and I don t want to waste time on bad reviewing    I ll leave it at that   ',
 'phenomenal food   service and ambiance',
 'I wouldn t return',
 'definitely worth venture off the strip for the pork belly   will return next time I m in Vegas',
 'this place be way too overpriced for mediocre food',
 'Penne vodka excellent',
 'they have a good selection of food include a massive meatloaf sandwich   a crispy chicken wrap   a delish tuna melt and some tasty burger',
 'the management be rude',
 'Delicious NYC bagel   good selection of cream cheese   real Lox with caper even',
 'Great Subway   in fact it s so good when you come here every other Subway will not meet your expectation',
 'I have a seriously solid breakfast here',
 'this be one of the good bar with food in Vegas',
 'he be extremely rude and really   there be so many other restaurant I would love to dine at during a weekend in Vegas',
 'my drink be never empty and he make some really great menu suggestion',
 'Don t do it    ',
 'the waiter wasn t helpful or friendly and rarely check on we',
 'my husband and I eat lunch here and be very disappointed with the food and service',
 'and the red curry have so much bamboo shoot and wasn t very tasty to I',
 'nice blanket of moz over top but I feel like this be do to cover up the subpar food',
 'the bathroom be clean and the place itself be well decorate',
 'the menu be always change   food quality be go down    service be extremely slow',
 'the service be a little slow    consider that be serve by 3 people server so the food be come in a slow pace',
 'I give it 2 thumb down',
 'we watch our waiter pay a lot more attention to other table and ignore we',
 'my fianc   and I come in the middle of the day and we be greet and seat right away',
 'this be a great restaurant at the Mandalay Bay',
 'we wait for forty five minute in vain',
 'Crostini that come with the salad be stale',
 'some highlight    great quality nigiri here',
 'the staff be friendly and the joint be always clean',
 'this be a different cut than the piece the other day but still wonderful and tender s well as well flavor',
 'I order the Voodoo pasta and it be the first time I d have really excellent pasta since going gluten free several year ago',
 'this place be good',
 'unfortunately   we must have hit the bakery on leftover day because everything we order be STALE',
 'I come back today since they relocate and still not impressed',
 'I be seat immediately',
 'their menu be diverse   and reasonably price',
 'avoid at all cost',
 'restaurant be always full but never a wait',
 'DELICIOUS  ',
 'this place be hand down one of the good place to eat in the Phoenix metro area',
 'so don t go there if you be look for good food   ',
 'I ve never be treat so bad',
 'Bacon be hella salty',
 'we also order the spinach and avocado salad   the ingredient be sad and the dressing literally have zero taste',
 'this really be how Vegas fine dining use to be   right down to the menu hand to the lady that have no price list',
 'the waitress be very friendly',
 'lordy   the Khao Soi be a dish that be not to be miss for curry lover',
 'everything on the menu be terrific and we be also thrilled that they make amazing accommodation for our vegetarian daughter',
 'perhaps I catch they on an off night judge by the other review   but I m not inspire to go back',
 'the service here leave a lot to be desire',
 'the atmosphere be modern and hip   while maintain a touch of coziness',
 'not a weekly haunt   but definitely a place to come back to every once in a while',
 'we literally sit there for 20 minute with no one ask to take our order',
 'the burger have absolutely no flavor    the meat itself be totally bland   the burger be overcook and there be no charcoal flavor',
 'I also decide not to send it back because our waitress look like she be on the verge of have a heart attack',
 'I dress up to be treat so rudely',
 'it be probably dirt',
 'love this place   hit the spot when I want something healthy but not lack in quantity or flavor',
 'I order the Lemon raspberry ice cocktail which be also incredible',
 'the food suck   which we expect but it suck more than we could have imagine',
 'interesting decor',
 'what I really like there be the crepe station',
 'also be serve hot bread and butter   and home make potato chip with bacon bit on top     very original and very good',
 'you can watch they prepare the delicious food  ',
 'both of the egg roll be fantastic',
 'when my order arrive   one of the gyro be miss',
 'I have a salad with the wing   and some ice cream for dessert and leave feel quite satisfied',
 'I m not really sure how Joey s be vote good hot dog in the Valley by reader of Phoenix Magazine',
 'the good place to go for a tasty bowl of Pho',
 'the live music on Fridays totally blow',
 'I ve never be more insulted or feel disrespected',
 'very friendly staff',
 'it be worth the drive',
 'I have hear good thing about this place   but it exceed every hope I could have dream of',
 'food be great and so be the serivce',
 'the warm beer didn t help',
 'great brunch spot',
 'service be friendly and invite',
 'very good lunch spot',
 'I ve live here since 1979 and this be the first   and last   time I ve step foot into this place',
 'the bad experience ever',
 'must have be an off night at this place',
 'the side be delish    mix mushroom   yukon gold puree   white corn    beateous',
 'if that bug never show up I would have give a 4 for sure   but on the other side of the wall where this bug be climb be the kitchen',
 'for about 10 minute   we we re wait for her salad when we realize that it wasn t come any time soon',
 'my friend love the salmon tartar',
 'Won t go back',
 'extremely Tasty',
 'Waitress be good though',
 'soggy and not good',
 'the jamaican mojito be delicious',
 'which be small and not worth the price',
 '   the food be rich so order accordingly',
 'the shower area be outside so you can only rinse   not take a full shower   unless you don t mind be nude for everyone to see',
 'the service be a bit lacking',
 'Lobster Bisque   Bussell Sprouts   Risotto   Filet all need salt and pepper   and of course there be none at the table',
 'hopefully this bode for they go out of business and someone who can cook can come in',
 'it be either too cold   not enough flavor or just bad',
 'I love the bacon wrap date',
 'this be an unbelievable bargain',
 'the folk at Otto always make we feel so welcome and special',
 'as for the   main    also uninspired',
 'this be the place where I first have pho and it be amazing  ',
 'this wonderful experience make this place a must stop whenever we be in town again',
 'if the food isn t bad enough for you   then enjoy deal with the world s worst annoying drunk people',
 'very very fun chef',
 'order a double cheeseburger    get a single patty that be fall apart   picture upload   yeah   still suck',
 'great place to have a couple drink and watch any and all sporting event as the wall be cover with tv s',
 'if it be possible to give they zero star   they d have it',
 'the description say   yum yum sauce   and another say   eel sauce    yet another say   spicy mayo     well none of the roll have sauce on they',
 'I d say that would be the hard decision     honestly   all of M s dish taste how they be suppose to taste   amazing  ',
 'if she have not roll the eye we may have stay     not sure if we will go back and try it again',
 'everyone be very attentive   provide excellent customer service',
 'horrible    don t waste your time and money',
 'now this dish be quite flavourful',
 'by this time our side of the restaurant be almost empty so there be no excuse',
 '  it wasn t busy either   also   the building be freeze cold',
 'like the other reviewer say   you couldn t pay I to eat at this place again  ',
 '  drink take close to 30 minute to come out at one point',
 'seriously flavorful delight   folk',
 'much well than the other AYCE sushi place I go to in Vegas',
 'the lighting be just dark enough to set the mood',
 'base on the sub par service I receive and no effort to show their gratitude for my business I win t be go back',
 'owner s be really great people  ',
 'there be nothing privileged about work eat there',
 'the greek dressing be very creamy and flavorful',
 'overall   I don t think that I would take my parent to this place again because they make most of the similar complaint that I silently feel too',
 'now the pizza itself be good the peanut sauce be very tasty',
 'we have 7 at our table and the service be pretty fast',
 'fantastic service here',
 'I as well would ve give godfather zero star if possible',
 'they know how to make they here',
 'very tough and very short on flavor',
 'I hope this place stick around',
 'I have be in more than a few bar in Vegas   and do not ever recall be charge for tap water',
 'the restaurant atmosphere be exquisite',
 'good service   very clean   and inexpensive   to boot',
 'the seafood be fresh and generous in portion',
 'plus   it s only 8 buck',
 'the service be not up to par   either',
 'thus far   have only visit twice and the food be absolutely delicious each time',
 'just as good as when I have it more than a year ago',
 'for a self proclaim coffee cafe   I be wildly disappointed',
 'the Veggitarian platter be out of this world',
 'you can not go wrong with any of the food here',
 'you can t beat that',
 'stop by this place while in Madison for the Ironman   very friendly   kind staff',
 'the chef be friendly and do a good job',
 'I ve have well   not only from dedicated boba tea spot   but even from Jenni Pho',
 'I like the patio and the service be outstanding',
 'the goat taco didn t skimp on the meat and wow what FLAVOR',
 'I think not again',
 'I have the mac salad and it be pretty bland so I will not be get that again',
 'I go to Bachi Burger on a friend s recommendation and be not disappointed',
 'service stink here',
 'I wait and wait',
 'this place be not quality sushi   it be not a quality restaurant',
 'I would definitely recommend the wing as well as the pizza',
 'Great Pizza and Salads',
 'thing that go wrong     they burn the saganaki',
 'we wait an hour for what be a breakfast I could have do 100 time well at home',
 'this place be amazing',
 'I hate to disagree with my fellow Yelpers   but my husband and I be so disappointed with this place',
 'wait 2 hour    never get either of our pizza as many other around we who come in later do',
 'just don t know why they be so slow',
 'the staff be great   the food be delish   and they have an incredible beer selection',
 'I live in the neighborhood so I be disappointed I win t be back here   because it be a convenient location',
 'I didn t know pull pork could be soooo delicious',
 'you get incredibly fresh fish   prepare with care',
 'before I go in to why I give a 1 star rating please know that this be my third time eat at Bachi burger before write a review',
 'I love the fact that everything on their menu be worth it',
 'never again will I be dine at this place',
 'the food be excellent and service be very good',
 'good beer    drink selection and good food selection',
 'please stay away from the shrimp stir fry noodle',
 'the potato chip order be sad     I could probably count how many chip be in that box and it be probably around 12',
 'food be really boring',
 'Good Service check',
 'this greedy corporation will never see another dime from I',
 'will never   ever go back',
 'as much as I d like to go back   I can t get pass the atrocious service and will never return',
 'in the summer   you can dine in a charming outdoor patio    so very delightful',
 'I do not expect this to be so good',
 'fantastic food',
 'she order a toasted english muffin that come out untoasted',
 'the food be very good',
 'never go back',
 'great food for the price   which be very high quality and house make',
 'the bus boy on the other hand be so rude',
 'by this point   my friend and I have basically figure out this place be a joke and didn t mind make it publicly and loudly know',
 'back to good BBQ   light fare   reasonable pricing and tell the public they be back to the old way',

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(output).toarray()

In [23]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [24]:
X.shape

(1000, 1742)

In [25]:
print(cv.get_feature_names_out())

['00' '10' '100' ... 'yum' 'yummy' 'zero']

In [26]:
data = pd.DataFrame(X, columns =cv.get_feature_names_out())

In [27]:
data[['wow','love','this','place']]

     wow  love  this  place
0      1     1     1      1
1      0     0     0      0
2      0     0     0      0
3      0     1     0      0
4      0     0     0      0
..   ...   ...   ...    ...
995    0     0     0      0
996    0     0     0      0
997    0     0     0      0
998    0     0     0      0
999    0     0     0      0

[1000 rows x 4 columns]

In [28]:
y=dataset['Liked']

In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,y,test_size=0.3, random_state=34)

In [30]:
from sklearn.naive_bayes import MultinomialNB
mm = MultinomialNB()
mm.fit(X_train, y_train)

MultinomialNB()

In [42]:
train_pred = mm.predict(X_train)
accuracy_score(y_train,train_pred)

0.9442857142857143

In [43]:
test_pred = mm.predict(X_test)

In [44]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,test_pred)

0.82